In [6]:
import os
import pandas as pd
import numpy as np

In [2]:
x=pd.read_csv('/Users/ryanmaloney/Downloads/Lines_MAD_2022.csv')

In [3]:
x

,7.960000000000000000e+02,5.350000000000000000e+02,7.030000000000000000e+02,2.290000000000000000e+02,2.390000000000000000e+02,7.870000000000000000e+02,8.430000000000000000e+02,5.020000000000000000e+02,7.210000000000000000e+02,8.790000000000000000e+02,...,4.050000000000000000e+02,3.210000000000000000e+02,8.530000000000000000e+02,3.770000000000000000e+02,1.770000000000000000e+02,8.570000000000000000e+02,2.560000000000000000e+02,2.170000000000000000e+02,7.300000000000000000e+01,8.190000000000000000e+02
0,0.043494,0.053915,0.055399,0.05698,0.057725,0.061947,0.063852,0.065657,0.066549,0.067051,...,0.090636,0.090986,0.09198,0.092097,0.094421,0.100422,0.100784,0.102941,0.110679,0.110824

In [13]:
x.columns=np.array(x.columns, dtype=int)

ValueError: invalid literal for int() with base 10: '7.960000000000000000e+02'

In [34]:
cnames=np.array(x.columns, dtype=str)
x.columns=cnames.astype(float)

In [32]:
cnames[0].astype(float)

796.0

In [35]:
x

,796.0,535.0,703.0,229.0,239.0,787.0,843.0,502.0,721.0,879.0,...,405.0,321.0,853.0,377.0,177.0,857.0,256.0,217.0,73.0,819.0
0,0.043494,0.053915,0.055399,0.05698,0.057725,0.061947,0.063852,0.065657,0.066549,0.067051,...,0.090636,0.090986,0.09198,0.092097,0.094421,0.100422,0.100784,0.102941,0.110679,0.110824

In [50]:
y=x.T

In [51]:
y.columns=["MAD"]

In [54]:
y.sort_values(by="MAD")

            MAD
796.0  0.043494
535.0  0.053915
703.0  0.055399
229.0  0.056980
239.0  0.057725
787.0  0.061947
843.0  0.063852
502.0  0.065657
721.0  0.066549
879.0  0.067051
45.0   0.067132
109.0  0.067528
517.0  0.067939
738.0  0.068807
85.0   0.074444
907.0  0.075860
426.0  0.076951
208.0  0.077072
808.0  0.079912
181.0  0.081830
757.0  0.083958
802.0  0.088746
405.0  0.090636
321.0  0.090986
853.0  0.091980
377.0  0.092097
177.0  0.094421
857.0  0.100422
256.0  0.100784
217.0  0.102941
73.0   0.110679
819.0  0.110824

In [ ]:
# I have 796, 535, 45, 105


703, 229, 819, 73, 85, 907, 426, 208